import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.scss";
import { Header } from "widgets/header";
import { Footer } from "widgets/footer";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Furniro - furniture store",
  description: "Generated by create next app",
  icons: {
    icon: "/img/utils/logo-icon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
